# -*- coding: utf-8 -*-

translations = {
    "en": {
        "loginB": "Log in",
        "signB": "Sign up",
        "ssignB": "Admin sign up",
        "logoutB": "Log out",
        "homeB": "Home",
        "publishB": "Publish",
        "publishedB": "Published articles",
        "aboutT": "About",
        "langT": "Language",
        "contentTableT": "Articles you subscribed",
        "contentPublishedTableT": "Articles you published",
        "controlTableT": "Articles published",
        "contentsT": "Contents",
        "titleT": "Title",
        "classesT": "Class",
        "classesT2": "Class:",
        "operationsT": "Operations",
        "deleteB": "DELETE",
        "authorT": "Author",
        "indexIntro1": "Organize life",
        "indexIntro2": "Then go enjoy it...",
        "indexIntro3": "Life can feel overwhelming, but it doesn’t have to. We let you keep track of everything in one place, so you can get it all done and enjoy more peace of mind along the way.",
        "indexIntro4": "Never worry about forgetting things again",
        "indexIntro5": "Let we remember it all for you. You can get tasks out of your head and onto your to-do list anytime, anywhere, on any device–even offline.",
        "indexIntroB": "Sign up now and try!",
        "usernamePlaceHolder": "User name",
        "useridPlaceHolder": "User ID",
        "passwordPlaceHolder": "Password",
        "loginPageHint": "Please input information to log in!",
        "signupPageHint": "Please input information to sign up!",
        "publishPageHint": "Please input information to publish!",
        "useridSignHint": "User ID(use:0-9a-Z_;length:4-16)",
        "passwordSignHint": "Password(length:6-16;no spaces or brackets)",
        "sectionsChooseT": "Choose what you want to subscribe:",
        "backhomeB": "Go home",
        "logoutInfoT": "Logged out!",
        "classesWrongT": "[NONE]",
        "loggedinIndexInfo1": "Logged in as: ",
        "loggedinIndexInfo2": " !",
        "notloggedinIndexInfo": "Not logged in!",
        "logoutBeforeSignInfo": "You already logged in! Please log out first!",
        "logoutBeforeLoginInfo": "You already logged in! Please log out first!",
        "errorRefreshInfo": "Error, please refresh!",
        "passwordErrorInfo": "Password not suitble!",
        "useridErrorInfo": "User ID not suitble or already used!",
        "signupSucInfo1": "Successfully signed as ",
        "signupSucInfo2": " , will go to the log in page!",
        "loginfailInfo": "User ID or password error! Please check!",
        "usernameAvaInfo": "User ID available!",
        "usernameNotAvaInfo": "User ID not available!",
        "loginFirstInfo": "Please log in first!",
        "cannotpublishInfo": "You don't have permission to publish!",
        "publishSucInfo": "Successfully published: ",
        "changedLangInfo": "Successfully changed language!",
        "securecodeErrorInfo": "Your secure code isn't suitable!",
        "secureSignHint": "Secure code",
        "NoneUser": "[DELETED]",
        "cannotintoInfo": "You don't have permission to do so!",
        "levelT": "Level of code(1-4)",
        "levelT2": "Level of code",
        "numT": "Number",
        "createB": "Create",
        "statusT": "Status",
        "timeT": "Time of created",
        "typenameHint": "Name",
        "typetextHint": "Stored value",
        "controltypesSignHint": "Control classes of articles",
        "controlarticlesHint": "Control articles",
        "normalusersT": "Normal users"
    },

    "zhCN": {
        "loginB": "登陆",
        "signB": "注册",
        "ssignB": "管理员注册",
        "logoutB": "注销",
        "homeB": "主页",
        "publishB": "发布信息",
        "publishedB": "查看发布的信息",
        "aboutT": "关于",
        "langT": "语言",
        "contentTableT": "你订阅分类中的文章",
        "contentPublishedTableT": "你发布的文章",
        "controlTableT": "发布的文章",
        "contentsT": "内容",
        "titleT": "标题",
        "classesT": "分类",
        "classesT2": "分类：",
        "operationsT": "操作",
        "deleteB": "删除",
        "authorT": "作者",
        "indexIntro1": "规划生活",
        "indexIntro2": "然后享受生活……",
        "indexIntro3": "生活可能让您倍感焦虑，但实际上您大可不必如此。我们可以让您跟进所有事情，这样您就可以轻松完成它们并享受之后的宁静时光。",
        "indexIntro4": "再也不用担心会忘记任何事",
        "indexIntro5": "让我们帮您记住所有事情。您可以随时随地将任务从您的脑海中移至您任何设备的任务清单上，即使离线也没问题。",
        "indexIntroB": "立即注册开始体验",
        "usernamePlaceHolder": "用户名",
        "useridPlaceHolder": "用户ID",
        "passwordPlaceHolder": "密码",
        "loginPageHint": "请输入信息后登陆！",
        "signupPageHint": "请输入信息后注册！",
        "publishPageHint": "请输入信息后发布！",
        "useridSignHint": "用户ID（4-16位，使用英文数字下划线）",
        "passwordSignHint": "密码（6-16位，不含空格括号）",
        "sectionsChooseT": "选择你想要订阅的内容：",
        "backhomeB": "返回主页",
        "logoutInfoT": "已注销！",
        "classesWrongT": "[已失效]",
        "loggedinIndexInfo1": "已作为 ",
        "loggedinIndexInfo2": " 登陆！",
        "notloggedinIndexInfo": "尚未登陆！",
        "logoutBeforeSignInfo": "您已经登陆，请先注销之后再注册！",
        "logoutBeforeLoginInfo": "您已经登陆，请先注销之后再登陆！",
        "errorRefreshInfo": "出错了，请刷新页面！",
        "passwordErrorInfo": "密码不合法！",
        "useridErrorInfo": "用户ID不合法或者已经被注册！",
        "signupSucInfo1": "已经成功注册为 ",
        "signupSucInfo2": " ，将进入登陆页面！",
        "loginfailInfo": "用户ID或密码出错，请检查后再登陆！",
        "usernameAvaInfo": "用户ID可用！",
        "usernameNotAvaInfo": "用户ID不可用！",
        "loginFirstInfo": "请先登陆再操作！",
        "cannotpublishInfo": "您没有发布信息的权限！",
        "publishSucInfo": "成功发布了消息： ",
        "changedLangInfo": "成功更改语言！",
        "securecodeErrorInfo": "安全码错误！",
        "secureSignHint": "安全码",
        "NoneUser": "[已封号]",
        "cannotintoInfo": "您没有权限！",
        "levelT": "安全码级别(1-4)",
        "levelT2": "安全码级别",
        "numT": "个数",
        "createB": "创建",
        "statusT": "状态",
        "timeT": "创建时间",
        "typenameHint": "名称",
        "typetextHint": "存储名称",
        "controltypesSignHint": "管理发帖分类",
        "controlarticlesHint": "发帖管理",
        "normalusersT": "普通用户列表"
    },

    "zhTW": {
        "loginB": "登陸",
        "signB": "註冊",
        "ssignB": "管理員註冊",
        "logoutB": "註銷",
        "homeB": "主頁",
        "publishB": "發布信息",
        "publishedB": "查看發布的信息",
        "aboutT": "關於",
        "langT": "語言",
        "contentTableT": "你訂閱分類中的文章",
        "contentPublishedTableT": "你發布的文章",
        "controlTableT": "發布的文章",
        "contentsT": "內容",
        "titleT": "標題",
        "classesT": "分類",
        "classesT2": "分類：",
        "operationsT": "操作",
        "deleteB": "刪除",
        "authorT": "作者",
        "indexIntro1": "規劃生活",
        "indexIntro2": "然後享受生活……",
        "indexIntro3": "生活可能讓您倍感焦慮，但實際上您大可不必如此。我們可以讓您跟進所有事情，這樣您就可以輕鬆完成它們並享受之後的寧靜時光。",
        "indexIntro4": "再也不用擔心會忘記任何事",
        "indexIntro5": "讓我們幫您記住所有事情。您可以隨時隨地將任務從您的腦海中移至您任何設備的任務清單上，即使離線也沒問題。",
        "indexIntroB": "立即註冊開始體驗",
        "usernamePlaceHolder": "用戶名",
        "useridPlaceHolder": "用戶ID",
        "passwordPlaceHolder": "密碼",
        "loginPageHint": "請輸入信息後登陸！",
        "signupPageHint": "請輸入信息後註冊！",
        "publishPageHint": "請輸入信息後發布！",
        "useridSignHint": "用戶ID（4-16位，使用英文數字下劃線）",
        "passwordSignHint": "密碼（6-16位，不含空格括號）",
        "sectionsChooseT": "選擇你想要訂閱的內容：",
        "backhomeB": "返回主頁",
        "logoutInfoT": "已註銷！",
        "classesWrongT": "[已失效]",
        "loggedinIndexInfo1": "已作為 ",
        "loggedinIndexInfo2": " 登陸！",
        "notloggedinIndexInfo": "尚未登陸！",
        "logoutBeforeSignInfo": "您已經登陸，請先註銷之後再註冊！",
        "logoutBeforeLoginInfo": "您已經登陸，請先註銷之後再登陸！",
        "errorRefreshInfo": "出錯了，請刷新頁面！",
        "passwordErrorInfo": "密碼不合法！",
        "useridErrorInfo": "用戶ID不合法或者已經被註冊！",
        "signupSucInfo1": "已經成功註冊為 ",
        "signupSucInfo2": " ，將進入登陸頁面！",
        "loginfailInfo": "用戶ID或密碼出錯，請檢查後再登陸！",
        "usernameAvaInfo": "用戶ID可用！",
        "usernameNotAvaInfo": "用戶ID不可用！",
        "loginFirstInfo": "請先登陸再操作！",
        "cannotpublishInfo": "您沒有發布信息的權限！",
        "publishSucInfo": "成功發布了消息： ",
        "changedLangInfo": "成功更改語言！",
        "securecodeErrorInfo": "安全碼錯誤！",
        "secureSignHint": "安全碼",
        "NoneUser": "[已封號]",
        "cannotintoInfo": "您沒有權限！",
        "levelT": "安全碼級別(1-4)",
        "levelT2": "安全碼級別",
        "numT": "個數",
        "createB": "創建",
        "statusT": "狀態",
        "timeT": "創建時間",
        "typenameHint": "名稱",
        "typetextHint": "存儲名稱",
        "controltypesSignHint": "管理髮帖分類",
        "controlarticlesHint": "發帖管理",
        "normalusersT": "普通用戶列表"
    },

    "es": {
        "loginB": "iniciar sesión",
        "signB": "Registrarse",
        "ssignB": "Registro de administrador",
        "logoutB": "Cerrar sesión",
        "homeB": "Inicio",
        "publishB": "Publicación de información",
        "publishedB": "Ver información de la publicación",
        "aboutT": "Acerca de",
        "langT": "lenguaje",
        "contentTableT": "Usted se suscribe a los artículos en la categoría",
        "contentPublishedTableT": "Tu publicación",
        "controlTableT": "Publicación",
        "contentsT": "Contenido",
        "titleT": "Título",
        "classesT": "Categoría",
        "classesT2": "Categoría:",
        "operationsT": "Operación",
        "deleteB": "Eliminar",
        "authorT": "Autor",
        "indexIntro1": "Organiza tu vida",
        "indexIntro2": "Luego ve y disfrútala...",
        "indexIntro3": "La vida puede ser abrumadora, pero no tiene por qué ser así. Yo te permite hacerle seguimiento a todo en un solo lugar para que puedas lograr tus objetivos y disfrutar de una mayor tranquilidad en el proceso.",
        "indexIntro4": "No te preocupes por olvidar cosas nunca más",
        "indexIntro5": "Deja que yo recuerde todo por ti. Puedes sacar las cosas de tu cabeza y ponerlas en tu lista de tareas en cualquier momento y desde cualquier lugar. Incluso si no tienes conexión a internet.",
        "indexIntroB": "Regístrese ahora para comenzar",
        "usernamePlaceHolder": "Nombre de usuario",
        "useridPlaceHolder": "ID de usuario",
        "passwordPlaceHolder": "Contraseña",
        "loginPageHint": "¡Por favor inicie sesión después de iniciar sesión!",
        "signupPageHint": "¡Regístrese después de ingresar la información!",
        "publishPageHint": "¡Publica un mensaje!",
        "useridSignHint": "ID de usuario (números en inglés subrayados, 4-16 dígitos)",
        "passwordSignHint": "Contraseña (6-16 dígitos sin espacios entre paréntesis)",
        "sectionsChooseT": "Elija a qué desea suscribirse:",
        "backhomeB": "Volver a la página de inicio",
        "logoutInfoT": "¡Cerrar sesión!",
        "classesWrongT": "[EXPIRADO]",
        "loggedinIndexInfo1": "Como hecho",
        "loggedinIndexInfo2": "¡Iniciar sesión!",
        "notloggedinIndexInfo": "¡Aún no ha iniciado sesión!",
        "logoutBeforeSignInfo": "Ha iniciado sesión, cierre la sesión antes de registrarse!",
        "logoutBeforeLoginInfo": "Ha aterrizado, cierre la sesión antes de aterrizar!",
        "errorRefreshInfo": "Ha ocurrido un error, actualice la página",
        "passwordErrorInfo": "¡Contraseña inválida!",
        "useridErrorInfo": "¡La ID de usuario no es válida o ya se ha registrado!",
        "signupSucInfo1": "¡Se ha registrado correctamente como ",
        "signupSucInfo2": " , ingresará a la página de inicio de sesión!",
        "loginfailInfo": "Error de ID de usuario o contraseña, compruebe antes de aterrizar!",
        "usernameAvaInfo": "¡La identificación de usuario está disponible!",
        "usernameNotAvaInfo": "¡La identificación de usuario no está disponible!",
        "loginFirstInfo": "¡Por favor inicie sesión de nuevo!",
        "cannotpublishInfo":"¡No tienes permiso para publicar información!",
        "publishSucInfo": "Mensaje publicado con éxito:",
        "changedLangInfo": "¡Cambió el idioma correctamente!",
        "securecodeErrorInfo": "¡Error de código de seguridad!",
        "secureSignHint": "Código de seguridad",
        "NoneUser": "[ELIMINADO]",
        "cannotintoInfo": "¡No tienes permiso! ",
        "levelT": "Nivel de código(1-4)",
        "levelT2": "Nivel de código",
        "numT": "Número",
        "createB": "Crear",
        "statusT": "Estado",
        "timeT": "Crear tiempo",
        "typenameHint": "Nombre",
        "typetextHint": "Nombre de la tienda",
        "controltypesSignHint": "Administrar categorías de publicación",
        "controlarticlesHint": "Gestión de publicaciones",
        "normalusersT": "Usuarios ordinarios"
    }
}
